# Generated by Django 5.1.6 on 2025-08-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performed_actions', to='games.gameplayer')),
                ('targets', models.ManyToManyField(related_name='targeted_by_actions', to='games.gameplayer')),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.actiontype')),
            ],
        ),
    ]
