# Generated by Django 5.2.5 on 2025-08-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actiontype",
            name="phase",
            field=models.CharField(
                choices=[("day", "Day"), ("night", "Night")],
                max_length=10,
                default="day",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="actiontype",
            name="slug",
            field=models.SlugField(max_length=100, blank=True, null=True),
        ),
    ]
