# Generated by Django 5.2.4 on 2025-08-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_seed_action_types'),
        ('actions', '0004_actiontype_slug_unique'),
    ]

    operations = [
    ]
