# Generated by Django 5.2.4 on 2025-08-12 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_merge_20250810_1347'),
        ('games', '0005_game_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='phase',
            field=models.CharField(blank=True, choices=[('day', 'day'), ('night', 'night')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actiontype',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='action',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='games.game'),
        ),
        migrations.AlterField(
            model_name='action',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='targeted_actions', to='games.gameplayer'),
        ),
    ]
