# Generated by Django 5.2.4 on 2025-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
