# Generated by Django 5.2.4 on 2025-08-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_phase',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='day', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='eliminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='is_alive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, default='Untitled Game', max_length=100),
        ),
    ]
