# Generated by Django 5.2.4 on 2025-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_current_phase_game_round_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
