# Generated by Django 5.2.4 on 2025-08-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
