# Generated by Django 5.2.4 on 2025-08-14 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_ended_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameplayer',
            options={'ordering': ['seat_number', 'id']},
        ),
    ]
