# Generated by Django 5.1.6 on 2025-08-03 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actions', '0001_initial'),
        ('games', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10)),
                ('number', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Elimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('eliminated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.gamephase')),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.gamephase')),
            ],
        ),
        migrations.CreateModel(
            name='DaySpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('content', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.gamephase')),
            ],
        ),
        migrations.CreateModel(
            name='DayPhase',
            fields=[
            ],
            options={
                'verbose_name': 'Day Phase',
                'verbose_name_plural': 'Day Phases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logs.gamephase',),
        ),
        migrations.CreateModel(
            name='NightPhase',
            fields=[
            ],
            options={
                'verbose_name': 'Night Phase',
                'verbose_name_plural': 'Night Phases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('logs.gamephase',),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('day', 'روز'), ('night', 'شب')], max_length=10)),
                ('round_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actions.actiontype')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('game_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
                ('targets', models.ManyToManyField(related_name='logs_targeted', to='games.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='NightAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=30)),
                ('result', models.TextField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_actions', to='games.gameplayer')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.gamephase')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='night_targets', to='games.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('accuse', 'Accuse'), ('defend', 'Defend'), ('guess_mafia', 'Guess Mafia')], max_length=20)),
                ('guess_k', models.IntegerField(blank=True, null=True)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.dayspeech')),
                ('targets', models.ManyToManyField(related_name='day_targets', to='games.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_round', models.IntegerField(choices=[(1, 'First Round'), (2, 'Second Round')])),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.gamephase')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='games.gameplayer')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='games.gameplayer')),
            ],
        ),
        migrations.CreateModel(
            name='Will',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.gamephase')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
            ],
        ),
    ]
