# Generated by Django 5.2.4 on 2025-08-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtarget',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
