# Generated by Django 5.2.4 on 2025-08-13 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_ended_at'),
        ('logs', '0002_alter_logtarget_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='phase',
            field=models.CharField(choices=[('day', 'Day'), ('night', 'Night')], max_length=10),
        ),
        migrations.CreateModel(
            name='DayTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameplayer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'ordering': ['game_id', 'round_number', 'index'],
                'unique_together': {('game', 'round_number', 'index')},
            },
        ),
        migrations.AddField(
            model_name='log',
            name='day_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logs.dayturn'),
        ),
    ]
